#! /bin/bash

# Save the output of the setuprel.sh so that we know whether or not to run this on test servers

MANIFEST=$1

cd $CMSSW_BASE/src

if [ -f $MANIFEST ]
then
    rm $MANIFEST
fi

for PKG in *
do

    if [ "${PKG:0:5}" != "Panda" ]
    then
        find $PKG -type f -not -name "*.pyc" | grep -v "__init__.py" | sort | xargs sha1sum >> $MANIFEST
    fi

done

cd -
